storage:
  dbPath: /data/db
#needs chown 999 mounted log folder
#systemLog:
#  destination: syslog
##  path: /data/log/mongod.log
#  logAppend: true

net:
  port: 27017
  bindIp: 0.0.0.0

security:
  authorization: enabled
